FROM node:20-alpine AS build
WORKDIR /app

COPY package*.json ./

RUN npm ci --legacy-peer-deps

COPY . .

RUN npm run build -- --configuration=docker

FROM nginx:alpine
COPY --from=build /app/dist/DzenCodeTest_Front/browser /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]